name: Compression Tuning Examples
# Example: Different compression strategies for various use cases
#
# Storage options:
# 1. Local filesystem (shown below):
#    - Requires: self-hosted runners with persistent disk
#    - Fastest, no external dependencies
#
# 2. S3/GCS backends (add storage-provider, s3-*/gcs-* inputs):
#    - Works on: GitHub-hosted OR self-hosted runners
#    - Custom storage backend (actions/cache doesn't support this)
#
# These examples show how to tune compression for different scenarios.
# Note: zstd supports a --long=30 flag for workloads that need a larger decode window / more memory,
#       which can be useful for very large caches.
# Docs: https://github.com/amulya-labs/gha-opencache#compression

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # Auto compression (default) - detects zstd, falls back to gzip
  auto-compression:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      - uses: actions/checkout@v4

      - name: Cache with auto compression
        uses: amulya-labs/gha-opencache@v2
        with:
          path: node_modules
          key: auto-${{ hashFiles('package-lock.json') }}
          compression: auto

      - name: Install
        run: npm ci

  # Maximum compression - slower but smallest size
  max-compression:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Cache with maximum compression
        uses: amulya-labs/gha-opencache@v2
        with:
          path: node_modules
          key: max-${{ hashFiles('package-lock.json') }}
          compression: zstd
          compression-level: 19

      - name: Install
        run: npm ci

  # Fast compression - good for large caches
  fast-compression:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Cache with fast compression
        uses: amulya-labs/gha-opencache@v2
        with:
          path: |
            node_modules
            .next/cache
          key: fast-${{ hashFiles('package-lock.json') }}
          compression: zstd
          compression-level: 1

      - name: Install
        run: npm ci

  # No compression - fastest for small or pre-compressed data
  no-compression:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Cache without compression
        uses: amulya-labs/gha-opencache@v2
        with:
          path: dist
          key: dist-${{ github.sha }}
          compression: none

      - name: Build
        run: npm run build

  # Gzip compression - maximum compatibility
  gzip-compression:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Cache with gzip
        uses: amulya-labs/gha-opencache@v2
        with:
          path: ~/.cargo
          key: cargo-${{ hashFiles('Cargo.lock') }}
          compression: gzip
          compression-level: 6

      - name: Build
        run: cargo build
