# Example: Using Google Cloud Storage with service account key
#
# Prerequisites:
# 1. Create a GCS bucket: gsutil mb -p my-project gs://my-cache-bucket
# 2. Create a service account with Storage Object Admin role
# 3. Generate and download service account key JSON
# 4. Store the JSON content in GitHub secret GCP_SA_KEY
#
# See MIGRATION.md for detailed setup instructions

name: GCS Cache Example

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Authenticate with GCP using service account key
      - name: Set up GCP credentials
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > ${{ runner.temp }}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/gcp-key.json" >> $GITHUB_ENV

      # Cache node_modules using GCS
      - uses: amulya-labs/gha-opencache@v1
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
          storage-provider: gcs
          gcs-bucket: my-cache-bucket
          gcs-project: my-project

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      # Clean up credentials
      - name: Clean up GCP credentials
        if: always()
        run: rm -f ${{ runner.temp }}/gcp-key.json
