name: Go with Module Cache
# Example: Caching Go modules and build artifacts
#
# This action is designed for SELF-HOSTED RUNNERS with local filesystem cache.
# Cache is stored on the runner's disk at /srv/gha-cache/v1 (default).
#
# For GitHub-hosted runners, use actions/cache instead.
# Docs: https://github.com/amulya-labs/gha-opencache#examples

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner (e.g., [self-hosted, linux])

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: amulya-labs/gha-opencache@v1
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: go-mod-${{ runner.os }}-

      - name: Cache Go build
        uses: amulya-labs/gha-opencache@v1
        with:
          path: ~/.cache/go-build
          key: go-build-${{ runner.os }}-${{ hashFiles('**/*.go') }}
          restore-keys: go-build-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
