name: Node.js with Basic Cache
# Example: Basic Node.js dependency caching with restore-keys fallback
#
# Local filesystem storage (storage-provider: local):
# - Requires SELF-HOSTED RUNNERS with persistent disk
# - Cache stored on runner's disk at /srv/gha-cache (default)
# - Fast, no external dependencies
#
# For GitHub-hosted runners, use S3/GCS storage backends instead (see s3-*.yml, gcs-*.yml examples)
# Docs: https://github.com/amulya-labs/gha-opencache#quick-start

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner (e.g., [self-hosted, linux])

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: amulya-labs/gha-opencache@v1
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-
          # storage-provider: local  # Default: uses local filesystem on self-hosted runner
          # cache-path: /srv/gha-cache  # Default: where cache is stored on runner disk

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
