name: Python with pip Cache
# Example: Python pip package caching with multi-level restore-keys
#
# This action is designed for SELF-HOSTED RUNNERS with local filesystem cache.
# Cache is stored on the runner's disk at /srv/gha-cache/v1 (default).
#
# For GitHub-hosted runners, use actions/cache instead.
# Docs: https://github.com/amulya-labs/gha-opencache#examples

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: self-hosted  # Use your self-hosted runner (e.g., [self-hosted, linux])

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: amulya-labs/gha-opencache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-py${{ matrix.python-version }}-
            pip-${{ runner.os }}-
          # storage-provider: local  # Default: uses local filesystem on self-hosted runner

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
