name: Python with pip Cache
# Example: Python pip package caching with multi-level restore-keys
#
# Storage options:
# 1. Local filesystem (shown below):
#    - Requires: self-hosted runners with persistent disk
#    - Fastest, no external dependencies
#    - Cache stored at ~/.cache/gha-opencache (default)
#
# 2. S3/GCS backends (see s3-*.yml, gcs-*.yml):
#    - Works on: GitHub-hosted OR self-hosted runners
#    - Custom storage backend (actions/cache doesn't support this)
#    - Shared cache across multiple runners
#
# Docs: https://github.com/amulya-labs/gha-opencache#examples

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: self-hosted  # Use your self-hosted runner (e.g., [self-hosted, linux])

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: amulya-labs/gha-opencache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-py${{ matrix.python-version }}-
            pip-${{ runner.os }}-
          # storage-provider: local  # Default: uses local filesystem on self-hosted runner

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
