name: S3 Cache with MinIO
# Example: Using MinIO S3-compatible storage backend
# Docs: https://github.com/amulya-labs/gha-opencache#storage-backends

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache with MinIO
        uses: amulya-labs/gha-opencache@v1
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

          storage-provider: s3
          s3-bucket: github-actions-cache
          s3-endpoint: https://minio.example.com
          s3-region: us-east-1
          s3-force-path-style: true  # Required for MinIO
          s3-prefix: my-project/
          ttl-days: 7
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
